# Generated by Django 2.2.7 on 2019-11-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191113_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
