# Generated by Django 2.2.7 on 2019-11-14 10:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191114_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Business'), (2, 'Entertainment'), (3, 'General'), (4, 'Health'), (5, 'Science'), (6, 'Sports'), (7, 'Technology')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='interests',
            field=models.CharField(choices=[(1, 'Business'), (2, 'Entertainment'), (3, 'General'), (4, 'Health'), (5, 'Science'), (6, 'Sports'), (7, 'Technology')], max_length=10, null=True),
        ),
    ]
