# Generated by Django 2.2.7 on 2019-11-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191114_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='interests',
        ),
    ]
